version: '3'
services:

  tomcat-app:
    image: tomcat:latest
    container_name: tomcat-container
    ports:
      - "8082:8080"
    volumes:
      - ./target:/usr/local/tomcat/webapps/
      - ./src/main/resources/xeno.db:/usr/local/tomcat/xeno.db
    networks:
      - xenowiki-network


volumes:
  xenowiki-volume:
networks:
  xenowiki-network: